#%RAML 1.0 NamedExample
- exchangeName: test-exchange-v12
  bindQueues: test-queue3,test-queue6
  region: us-west-2
  exchangeStatus: Existing
- queueName: test-exchange-v1
  bindQueues: test-queue1,test-queue6
  region: us-west-2
  exchangeStatus: Existing