#%RAML 1.0 NamedExample
- appName: rodanandfields-common-utils-qa
  status: STARTED
  muleVersion: 3.9.3
  workers: 1
  workertype: 0.1 vCores
  DisableCloudhubLog: true
  staticIPsEnabled: false
  ipAddresses: []
