#%RAML 1.0 NamedExample
value:
   status: "400"
   errorCode: "1"
   developerMessage: "this is a technical description of what happened"
   userMessage: "this is an end-user friendly message description of what happened"
   moreInfo: "https://api.rodanandfields.com/resetSponsorLoad/v1"